version: "3.8"

services:
  app:
    build: .
    container_name: url_shortener_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app                # Código fonte para reload em dev
      - ./data:/app/data      # Banco SQLite persistente
      - ./prod.env:/app/.env  # Arquivo de ambiente (renomeie conforme usar)
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload